package HBML.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.EnumerationDescriptorBase;
import jetbrains.mps.smodel.runtime.EnumerationDescriptor;
import jetbrains.mps.lang.smodel.EnumerationLiteralsIndex;
import java.util.List;
import org.jetbrains.annotations.Nullable;
import org.jetbrains.annotations.NotNull;

public class EnumerationDescriptor_SensorType extends EnumerationDescriptorBase {

  public EnumerationDescriptor_SensorType() {
    super(0xb0b8832625824427L, 0x889661f7684b0da0L, 0xb6c10cfea61adbL, "SensorType", "r:662f0f43-f4fc-4ca0-87f9-029b3756b650(HBML.structure)/51440707317406427");
  }

  private final EnumerationDescriptor.MemberDescriptor myMember_TEMPERATURE_0 = new EnumerationDescriptor.MemberDescriptor("TEMPERATURE", "TEMPERATURE", 0xb6c10cfea61adcL, "r:662f0f43-f4fc-4ca0-87f9-029b3756b650(HBML.structure)/51440707317406428");
  private final EnumerationDescriptor.MemberDescriptor myMember_PRESSURE_0 = new EnumerationDescriptor.MemberDescriptor("PRESSURE", "PRESSURE", 0xb6c10cfea61addL, "r:662f0f43-f4fc-4ca0-87f9-029b3756b650(HBML.structure)/51440707317406429");
  private final EnumerationDescriptor.MemberDescriptor myMember_PROXIMITY_0 = new EnumerationDescriptor.MemberDescriptor("PROXIMITY", "PROXIMITY", 0xb6c10cfea61ae0L, "r:662f0f43-f4fc-4ca0-87f9-029b3756b650(HBML.structure)/51440707317406432");
  private final EnumerationDescriptor.MemberDescriptor myMember_ACCELEROMETER_0 = new EnumerationDescriptor.MemberDescriptor("ACCELEROMETER", "ACCELEROMETER", 0xb6c10cfea61ae4L, "r:662f0f43-f4fc-4ca0-87f9-029b3756b650(HBML.structure)/51440707317406436");
  private final EnumerationDescriptor.MemberDescriptor myMember_GAS_0 = new EnumerationDescriptor.MemberDescriptor("GAS", "GAS", 0xb6c10cfea61ae9L, "r:662f0f43-f4fc-4ca0-87f9-029b3756b650(HBML.structure)/51440707317406441");
  private final EnumerationDescriptor.MemberDescriptor myMember_SMOKE_0 = new EnumerationDescriptor.MemberDescriptor("SMOKE", "SMOKE", 0xb6c10cfea61aefL, "r:662f0f43-f4fc-4ca0-87f9-029b3756b650(HBML.structure)/51440707317406447");
  private final EnumerationDescriptor.MemberDescriptor myMember_VIDEO_SURVAILLANCE_CAMERA_0 = new EnumerationDescriptor.MemberDescriptor("VIDEO_SURVAILLANCE_CAMERA", "VIDEO_SURVAILLANCE_CAMERA", 0xb6c10cfea61af6L, "r:662f0f43-f4fc-4ca0-87f9-029b3756b650(HBML.structure)/51440707317406454");

  private final EnumerationLiteralsIndex myIndex = EnumerationLiteralsIndex.build(0xb0b8832625824427L, 0x889661f7684b0da0L, 0xb6c10cfea61adbL, 0xb6c10cfea61adcL, 0xb6c10cfea61addL, 0xb6c10cfea61ae0L, 0xb6c10cfea61ae4L, 0xb6c10cfea61ae9L, 0xb6c10cfea61aefL, 0xb6c10cfea61af6L);
  private final List<EnumerationDescriptor.MemberDescriptor> myMembers = new EnumerationDescriptorBase.MembersList(myIndex, myMember_TEMPERATURE_0, myMember_PRESSURE_0, myMember_PROXIMITY_0, myMember_ACCELEROMETER_0, myMember_GAS_0, myMember_SMOKE_0, myMember_VIDEO_SURVAILLANCE_CAMERA_0);

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getDefault() {
    return null;
  }

  @NotNull
  @Override
  public List<EnumerationDescriptor.MemberDescriptor> getMembers() {
    return myMembers;
  }

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getMember(@Nullable String memberName) {
    if (memberName == null) {
      return null;
    }
    switch (memberName) {
      case "TEMPERATURE":
        return myMember_TEMPERATURE_0;
      case "PRESSURE":
        return myMember_PRESSURE_0;
      case "PROXIMITY":
        return myMember_PROXIMITY_0;
      case "ACCELEROMETER":
        return myMember_ACCELEROMETER_0;
      case "GAS":
        return myMember_GAS_0;
      case "SMOKE":
        return myMember_SMOKE_0;
      case "VIDEO_SURVAILLANCE_CAMERA":
        return myMember_VIDEO_SURVAILLANCE_CAMERA_0;
    }
    return null;
  }

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getMember(long idValue) {
    int index = myIndex.index(idValue);
    if (index == -1) {
      return null;
    }
    return myMembers.get(index);
  }
}
