package HBML.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.EnumerationDescriptorBase;
import jetbrains.mps.smodel.runtime.EnumerationDescriptor;
import jetbrains.mps.lang.smodel.EnumerationLiteralsIndex;
import java.util.List;
import org.jetbrains.annotations.Nullable;
import org.jetbrains.annotations.NotNull;

public class EnumerationDescriptor_RoomType extends EnumerationDescriptorBase {

  public EnumerationDescriptor_RoomType() {
    super(0xb0b8832625824427L, 0x889661f7684b0da0L, 0x1c4a0aa7eed2492L, "RoomType", "r:662f0f43-f4fc-4ca0-87f9-029b3756b650(HBML.structure)/127403343607571602");
  }

  private final EnumerationDescriptor.MemberDescriptor myMember_KITCHEN_0 = new EnumerationDescriptor.MemberDescriptor("KITCHEN", "KITCHEN", 0x1c4a0aa7eed2493L, "r:662f0f43-f4fc-4ca0-87f9-029b3756b650(HBML.structure)/127403343607571603");
  private final EnumerationDescriptor.MemberDescriptor myMember_BATHROOM_0 = new EnumerationDescriptor.MemberDescriptor("BATHROOM", "BATHROOM", 0x1c4a0aa7eed2494L, "r:662f0f43-f4fc-4ca0-87f9-029b3756b650(HBML.structure)/127403343607571604");
  private final EnumerationDescriptor.MemberDescriptor myMember_LIVING_ROOM_0 = new EnumerationDescriptor.MemberDescriptor("LIVING_ROOM", "LIVING_ROOM", 0x1c4a0aa7eed24a3L, "r:662f0f43-f4fc-4ca0-87f9-029b3756b650(HBML.structure)/127403343607571619");
  private final EnumerationDescriptor.MemberDescriptor myMember_BEDROOM_0 = new EnumerationDescriptor.MemberDescriptor("BEDROOM", "BEDROOM", 0x1c4a0aa7eed249bL, "r:662f0f43-f4fc-4ca0-87f9-029b3756b650(HBML.structure)/127403343607571611");
  private final EnumerationDescriptor.MemberDescriptor myMember_HALWAY_0 = new EnumerationDescriptor.MemberDescriptor("HALWAY", "HALWAY", 0x1c4a0aa7eed24a8L, "r:662f0f43-f4fc-4ca0-87f9-029b3756b650(HBML.structure)/127403343607571624");
  private final EnumerationDescriptor.MemberDescriptor myMember_ENTRANCE_0 = new EnumerationDescriptor.MemberDescriptor("ENTRANCE", "ENTRANCE", 0x1c4a0aa7eed24aeL, "r:662f0f43-f4fc-4ca0-87f9-029b3756b650(HBML.structure)/127403343607571630");
  private final EnumerationDescriptor.MemberDescriptor myMember_STUDY_0 = new EnumerationDescriptor.MemberDescriptor("STUDY", "STUDY", 0x2335ec8254d7a984L, "r:662f0f43-f4fc-4ca0-87f9-029b3756b650(HBML.structure)/2537194009606465924");
  private final EnumerationDescriptor.MemberDescriptor myMember_STORAGE_ROOM_0 = new EnumerationDescriptor.MemberDescriptor("STORAGE_ROOM", "STORAGE_ROOM", 0x2335ec8254d7a98cL, "r:662f0f43-f4fc-4ca0-87f9-029b3756b650(HBML.structure)/2537194009606465932");
  private final EnumerationDescriptor.MemberDescriptor myMember_GARAGE_0 = new EnumerationDescriptor.MemberDescriptor("GARAGE", "GARAGE", 0x2335ec8254d7a995L, "r:662f0f43-f4fc-4ca0-87f9-029b3756b650(HBML.structure)/2537194009606465941");
  private final EnumerationDescriptor.MemberDescriptor myMember_LAUNDRY_ROOM_0 = new EnumerationDescriptor.MemberDescriptor("LAUNDRY_ROOM", "LAUNDRY_ROOM", 0x2335ec8254d7a99fL, "r:662f0f43-f4fc-4ca0-87f9-029b3756b650(HBML.structure)/2537194009606465951");
  private final EnumerationDescriptor.MemberDescriptor myMember_HOBBY_ROOM_0 = new EnumerationDescriptor.MemberDescriptor("HOBBY_ROOM", "HOBBY_ROOM", 0x2335ec8254d7a9aaL, "r:662f0f43-f4fc-4ca0-87f9-029b3756b650(HBML.structure)/2537194009606465962");
  private final EnumerationDescriptor.MemberDescriptor myMember_CELLAR_0 = new EnumerationDescriptor.MemberDescriptor("CELLAR", "CELLAR", 0x2335ec8254d7a9b6L, "r:662f0f43-f4fc-4ca0-87f9-029b3756b650(HBML.structure)/2537194009606465974");
  private final EnumerationDescriptor.MemberDescriptor myMember_LUNCHROOOM_0 = new EnumerationDescriptor.MemberDescriptor("LUNCHROOOM", "LUNCHROOOM", 0x2335ec8254d7a9c3L, "r:662f0f43-f4fc-4ca0-87f9-029b3756b650(HBML.structure)/2537194009606465987");
  private final EnumerationDescriptor.MemberDescriptor myMember_STAIRS_0 = new EnumerationDescriptor.MemberDescriptor("STAIRS", "STAIRS", 0x2335ec8254d7a9d1L, "r:662f0f43-f4fc-4ca0-87f9-029b3756b650(HBML.structure)/2537194009606466001");

  private final EnumerationLiteralsIndex myIndex = EnumerationLiteralsIndex.build(0xb0b8832625824427L, 0x889661f7684b0da0L, 0x1c4a0aa7eed2492L, 0x1c4a0aa7eed2493L, 0x1c4a0aa7eed2494L, 0x1c4a0aa7eed24a3L, 0x1c4a0aa7eed249bL, 0x1c4a0aa7eed24a8L, 0x1c4a0aa7eed24aeL, 0x2335ec8254d7a984L, 0x2335ec8254d7a98cL, 0x2335ec8254d7a995L, 0x2335ec8254d7a99fL, 0x2335ec8254d7a9aaL, 0x2335ec8254d7a9b6L, 0x2335ec8254d7a9c3L, 0x2335ec8254d7a9d1L);
  private final List<EnumerationDescriptor.MemberDescriptor> myMembers = new EnumerationDescriptorBase.MembersList(myIndex, myMember_KITCHEN_0, myMember_BATHROOM_0, myMember_LIVING_ROOM_0, myMember_BEDROOM_0, myMember_HALWAY_0, myMember_ENTRANCE_0, myMember_STUDY_0, myMember_STORAGE_ROOM_0, myMember_GARAGE_0, myMember_LAUNDRY_ROOM_0, myMember_HOBBY_ROOM_0, myMember_CELLAR_0, myMember_LUNCHROOOM_0, myMember_STAIRS_0);

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getDefault() {
    return null;
  }

  @NotNull
  @Override
  public List<EnumerationDescriptor.MemberDescriptor> getMembers() {
    return myMembers;
  }

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getMember(@Nullable String memberName) {
    if (memberName == null) {
      return null;
    }
    switch (memberName) {
      case "KITCHEN":
        return myMember_KITCHEN_0;
      case "BATHROOM":
        return myMember_BATHROOM_0;
      case "LIVING_ROOM":
        return myMember_LIVING_ROOM_0;
      case "BEDROOM":
        return myMember_BEDROOM_0;
      case "HALWAY":
        return myMember_HALWAY_0;
      case "ENTRANCE":
        return myMember_ENTRANCE_0;
      case "STUDY":
        return myMember_STUDY_0;
      case "STORAGE_ROOM":
        return myMember_STORAGE_ROOM_0;
      case "GARAGE":
        return myMember_GARAGE_0;
      case "LAUNDRY_ROOM":
        return myMember_LAUNDRY_ROOM_0;
      case "HOBBY_ROOM":
        return myMember_HOBBY_ROOM_0;
      case "CELLAR":
        return myMember_CELLAR_0;
      case "LUNCHROOOM":
        return myMember_LUNCHROOOM_0;
      case "STAIRS":
        return myMember_STAIRS_0;
    }
    return null;
  }

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getMember(long idValue) {
    int index = myIndex.index(idValue);
    if (index == -1) {
      return null;
    }
    return myMembers.get(index);
  }
}
