package HBML.structure;

/*Generated by MPS */

import jetbrains.mps.lang.smodel.LanguageConceptIndex;
import jetbrains.mps.lang.smodel.LanguageConceptIndexBuilder;
import jetbrains.mps.smodel.adapter.ids.SConceptId;
import org.jetbrains.mps.openapi.language.SAbstractConcept;

public final class LanguageConceptSwitch {
  private final LanguageConceptIndex myIndex;
  public static final int Door = 0;
  public static final int Floor = 1;
  public static final int House = 2;
  public static final int OuterSpace = 3;
  public static final int Passage = 4;
  public static final int Room = 5;
  public static final int Space = 6;

  public LanguageConceptSwitch() {
    LanguageConceptIndexBuilder builder = new LanguageConceptIndexBuilder(0xb0b8832625824427L, 0x889661f7684b0da0L);
    builder.put(0x2335ec8254d7aa11L, Door);
    builder.put(0x7a62d4fd116b833dL, Floor);
    builder.put(0x7a62d4fd116b5067L, House);
    builder.put(0x2335ec8254df69eaL, OuterSpace);
    builder.put(0x2335ec8254d7aa09L, Passage);
    builder.put(0x1c4a0aa7eed248fL, Room);
    builder.put(0x1c4a0aa7eed2481L, Space);
    myIndex = builder.seal();
  }

  /*package*/ int index(SConceptId cid) {
    return myIndex.index(cid);
  }

  public int index(SAbstractConcept concept) {
    return myIndex.index(concept);
  }
}
