package HBML.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.BaseStructureAspectDescriptor;
import jetbrains.mps.smodel.runtime.ConceptDescriptor;
import jetbrains.mps.smodel.runtime.EnumerationDescriptor;
import jetbrains.mps.smodel.runtime.ConstrainedStringDatatypeDescriptor;
import jetbrains.mps.smodel.runtime.ConstrainedStringDatatypeDescriptorImpl;
import java.util.Collection;
import java.util.Arrays;
import org.jetbrains.annotations.Nullable;
import jetbrains.mps.smodel.adapter.ids.SConceptId;
import jetbrains.mps.smodel.runtime.DataTypeDescriptor;
import org.jetbrains.mps.openapi.language.SAbstractConcept;
import jetbrains.mps.smodel.runtime.impl.ConceptDescriptorBuilder2;
import jetbrains.mps.smodel.adapter.ids.MetaIdFactory;
import jetbrains.mps.smodel.adapter.ids.PrimitiveTypeId;

public class StructureAspectDescriptor extends BaseStructureAspectDescriptor {
  /*package*/ final ConceptDescriptor myConceptActuator = createDescriptorForActuator();
  /*package*/ final ConceptDescriptor myConceptController = createDescriptorForController();
  /*package*/ final ConceptDescriptor myConceptDevice = createDescriptorForDevice();
  /*package*/ final ConceptDescriptor myConceptDoor = createDescriptorForDoor();
  /*package*/ final ConceptDescriptor myConceptFloor = createDescriptorForFloor();
  /*package*/ final ConceptDescriptor myConceptHouse = createDescriptorForHouse();
  /*package*/ final ConceptDescriptor myConceptOuterSpace = createDescriptorForOuterSpace();
  /*package*/ final ConceptDescriptor myConceptPassage = createDescriptorForPassage();
  /*package*/ final ConceptDescriptor myConceptRoom = createDescriptorForRoom();
  /*package*/ final ConceptDescriptor myConceptSensor = createDescriptorForSensor();
  /*package*/ final ConceptDescriptor myConceptSpace = createDescriptorForSpace();
  /*package*/ final ConceptDescriptor myConceptWindow = createDescriptorForWindow();
  /*package*/ final EnumerationDescriptor myEnumerationActuatorType = new EnumerationDescriptor_ActuatorType();
  /*package*/ final EnumerationDescriptor myEnumerationDeviceType = new EnumerationDescriptor_DeviceType();
  /*package*/ final EnumerationDescriptor myEnumerationDoorType = new EnumerationDescriptor_DoorType();
  /*package*/ final EnumerationDescriptor myEnumerationGroundType = new EnumerationDescriptor_GroundType();
  /*package*/ final EnumerationDescriptor myEnumerationOuterSpaceType = new EnumerationDescriptor_OuterSpaceType();
  /*package*/ final EnumerationDescriptor myEnumerationRoomType = new EnumerationDescriptor_RoomType();
  /*package*/ final EnumerationDescriptor myEnumerationSensorType = new EnumerationDescriptor_SensorType();
  /*package*/ final ConstrainedStringDatatypeDescriptor myCSDatatypeDateMY = new ConstrainedStringDatatypeDescriptorImpl(0xb0b8832625824427L, 0x889661f7684b0da0L, 0x7a62d4fd116d6ea9L, "DateMY", "r:662f0f43-f4fc-4ca0-87f9-029b3756b650(HBML.structure)/8818845203729051305", "^(((0)[0-9])|((1)[0-2]))(\\/)\\d{4}$");
  private final LanguageConceptSwitch myIndexSwitch;

  public StructureAspectDescriptor() {
    myIndexSwitch = new LanguageConceptSwitch();
  }


  @Override
  public void reportDependencies(jetbrains.mps.smodel.runtime.StructureAspectDescriptor.Dependencies deps) {
    deps.extendedLanguage(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, "jetbrains.mps.lang.core");
  }

  @Override
  public Collection<ConceptDescriptor> getDescriptors() {
    return Arrays.asList(myConceptActuator, myConceptController, myConceptDevice, myConceptDoor, myConceptFloor, myConceptHouse, myConceptOuterSpace, myConceptPassage, myConceptRoom, myConceptSensor, myConceptSpace, myConceptWindow);
  }

  @Override
  @Nullable
  public ConceptDescriptor getDescriptor(SConceptId id) {
    switch (myIndexSwitch.index(id)) {
      case LanguageConceptSwitch.Actuator:
        return myConceptActuator;
      case LanguageConceptSwitch.Controller:
        return myConceptController;
      case LanguageConceptSwitch.Device:
        return myConceptDevice;
      case LanguageConceptSwitch.Door:
        return myConceptDoor;
      case LanguageConceptSwitch.Floor:
        return myConceptFloor;
      case LanguageConceptSwitch.House:
        return myConceptHouse;
      case LanguageConceptSwitch.OuterSpace:
        return myConceptOuterSpace;
      case LanguageConceptSwitch.Passage:
        return myConceptPassage;
      case LanguageConceptSwitch.Room:
        return myConceptRoom;
      case LanguageConceptSwitch.Sensor:
        return myConceptSensor;
      case LanguageConceptSwitch.Space:
        return myConceptSpace;
      case LanguageConceptSwitch.Window:
        return myConceptWindow;
      default:
        return null;
    }
  }

  @Override
  public Collection<DataTypeDescriptor> getDataTypeDescriptors() {
    return Arrays.asList(myEnumerationActuatorType, myEnumerationDeviceType, myEnumerationDoorType, myEnumerationGroundType, myEnumerationOuterSpaceType, myEnumerationRoomType, myEnumerationSensorType, myCSDatatypeDateMY);
  }

  /*package*/ int internalIndex(SAbstractConcept c) {
    return myIndexSwitch.index(c);
  }

  private static ConceptDescriptor createDescriptorForActuator() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("HBML", "Actuator", 0xb0b8832625824427L, 0x889661f7684b0da0L, 0xb6c10cfea61a47L);
    b.class_(false, false, false);
    b.parent(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L);
    b.origin("r:662f0f43-f4fc-4ca0-87f9-029b3756b650(HBML.structure)/51440707317406279");
    b.version(2);
    b.property("type", 0xb6c10cfea61a4aL).type(MetaIdFactory.dataTypeId(0xb0b8832625824427L, 0x889661f7684b0da0L, 0xb6c10cfea61a56L)).origin("51440707317406282").done();
    b.property("model", 0x133753e11ae4ebb5L).type(PrimitiveTypeId.STRING).origin("1384667636723674037").done();
    b.associate("device", 0xb6c10cfea61b97L).target(0xb0b8832625824427L, 0x889661f7684b0da0L, 0xb6c10cfea61b6eL).optional(false).origin("51440707317406615").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForController() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("HBML", "Controller", 0xb0b8832625824427L, 0x889661f7684b0da0L, 0xb6c10cfea61a42L);
    b.class_(false, false, false);
    b.parent(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L);
    b.origin("r:662f0f43-f4fc-4ca0-87f9-029b3756b650(HBML.structure)/51440707317406274");
    b.version(2);
    b.property("model", 0xb6c10cfea61a45L).type(PrimitiveTypeId.STRING).origin("51440707317406277").done();
    b.property("os", 0x133753e11ae4ebbbL).type(PrimitiveTypeId.STRING).origin("1384667636723674043").done();
    b.property("osVersion", 0x133753e11ae4ebbeL).type(PrimitiveTypeId.STRING).origin("1384667636723674046").done();
    b.aggregate("actuators", 0xb6c10cfea61b25L).target(0xb0b8832625824427L, 0x889661f7684b0da0L, 0xb6c10cfea61a47L).optional(false).ordered(true).multiple(true).origin("51440707317406501").done();
    b.aggregate("sensors", 0x19140125248cc76dL).target(0xb0b8832625824427L, 0x889661f7684b0da0L, 0xb6c10cfea61a84L).optional(false).ordered(true).multiple(true).origin("1807070609521035117").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForDevice() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("HBML", "Device", 0xb0b8832625824427L, 0x889661f7684b0da0L, 0xb6c10cfea61b6eL);
    b.class_(false, false, false);
    b.parent(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L);
    b.origin("r:662f0f43-f4fc-4ca0-87f9-029b3756b650(HBML.structure)/51440707317406574");
    b.version(2);
    b.property("type", 0xb6c10cfea61b71L).type(MetaIdFactory.dataTypeId(0xb0b8832625824427L, 0x889661f7684b0da0L, 0xb6c10cfea61afeL)).origin("51440707317406577").done();
    b.property("model", 0x133753e11ae4ebb8L).type(PrimitiveTypeId.STRING).origin("1384667636723674040").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForDoor() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("HBML", "Door", 0xb0b8832625824427L, 0x889661f7684b0da0L, 0x2335ec8254d7aa11L);
    b.class_(false, false, false);
    b.super_("HBML.structure.Passage", 0xb0b8832625824427L, 0x889661f7684b0da0L, 0x2335ec8254d7aa09L);
    b.origin("r:662f0f43-f4fc-4ca0-87f9-029b3756b650(HBML.structure)/2537194009606466065");
    b.version(2);
    b.property("type", 0x2335ec8254d7aa12L).type(MetaIdFactory.dataTypeId(0xb0b8832625824427L, 0x889661f7684b0da0L, 0x2335ec8254d7a9fbL)).origin("2537194009606466066").done();
    b.property("width", 0x2335ec8254d7aa14L).type(MetaIdFactory.dataTypeId(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0x10324579ea7L)).origin("2537194009606466068").done();
    b.property("height", 0x2335ec8254d7aa17L).type(MetaIdFactory.dataTypeId(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0x10324579ea7L)).origin("2537194009606466071").done();
    b.property("doorsNumber", 0x7f0c6ecade11e127L).type(PrimitiveTypeId.INTEGER).origin("9154813960125538599").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForFloor() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("HBML", "Floor", 0xb0b8832625824427L, 0x889661f7684b0da0L, 0x7a62d4fd116b833dL);
    b.class_(false, false, false);
    b.parent(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L);
    b.origin("r:662f0f43-f4fc-4ca0-87f9-029b3756b650(HBML.structure)/8818845203728925501");
    b.version(2);
    b.property("level", 0x7a62d4fd116b8342L).type(PrimitiveTypeId.INTEGER).origin("8818845203728925506").done();
    b.aggregate("rooms", 0x1c4a0aa7eed248dL).target(0xb0b8832625824427L, 0x889661f7684b0da0L, 0x1c4a0aa7eed248fL).optional(false).ordered(true).multiple(true).origin("127403343607571597").done();
    b.aggregate("outerSpaces", 0x6eca1909640a6303L).target(0xb0b8832625824427L, 0x889661f7684b0da0L, 0x2335ec8254df69eaL).optional(true).ordered(true).multiple(true).origin("7983220817591427843").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForHouse() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("HBML", "House", 0xb0b8832625824427L, 0x889661f7684b0da0L, 0x7a62d4fd116b5067L);
    b.class_(false, false, true);
    b.parent(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L);
    b.origin("r:662f0f43-f4fc-4ca0-87f9-029b3756b650(HBML.structure)/8818845203728912487");
    b.version(2);
    b.property("state", 0x7a62d4fd116b50aaL).type(PrimitiveTypeId.STRING).origin("8818845203728912554").done();
    b.property("address", 0x7a62d4fd116b50acL).type(PrimitiveTypeId.STRING).origin("8818845203728912556").done();
    b.property("city", 0x7a62d4fd116b8332L).type(PrimitiveTypeId.STRING).origin("8818845203728925490").done();
    b.property("province", 0x62a4375eb58dc226L).type(PrimitiveTypeId.STRING).origin("7107866991809905190").done();
    b.property("postalCode", 0x7a62d4fd116b8337L).type(PrimitiveTypeId.STRING).origin("8818845203728925495").done();
    b.property("buildingDate", 0x7a62d4fd116b50afL).type(MetaIdFactory.dataTypeId(0xb0b8832625824427L, 0x889661f7684b0da0L, 0x7a62d4fd116d6ea9L)).origin("8818845203728912559").done();
    b.aggregate("floors", 0x7a62d4fd116b8344L).target(0xb0b8832625824427L, 0x889661f7684b0da0L, 0x7a62d4fd116b833dL).optional(false).ordered(true).multiple(true).origin("8818845203728925508").done();
    b.aggregate("passages", 0x2335ec8254e140c2L).target(0xb0b8832625824427L, 0x889661f7684b0da0L, 0x2335ec8254d7aa09L).optional(true).ordered(true).multiple(true).origin("2537194009607094466").done();
    b.aggregate("doors", 0x7f0c6ecade107c08L).target(0xb0b8832625824427L, 0x889661f7684b0da0L, 0x2335ec8254d7aa11L).optional(true).ordered(true).multiple(true).origin("9154813960125447176").done();
    b.aggregate("controllers", 0x19140125248cc770L).target(0xb0b8832625824427L, 0x889661f7684b0da0L, 0xb6c10cfea61a42L).optional(true).ordered(true).multiple(true).origin("1807070609521035120").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForOuterSpace() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("HBML", "OuterSpace", 0xb0b8832625824427L, 0x889661f7684b0da0L, 0x2335ec8254df69eaL);
    b.class_(false, false, false);
    b.super_("HBML.structure.Space", 0xb0b8832625824427L, 0x889661f7684b0da0L, 0x1c4a0aa7eed2481L);
    b.parent(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L);
    b.origin("r:662f0f43-f4fc-4ca0-87f9-029b3756b650(HBML.structure)/2537194009606973930");
    b.version(2);
    b.property("type", 0x133753e11ae1f870L).type(MetaIdFactory.dataTypeId(0xb0b8832625824427L, 0x889661f7684b0da0L, 0x2335ec8254d7a9f2L)).origin("1384667636723480688").done();
    b.property("groundType", 0x133753e11ae1f874L).type(MetaIdFactory.dataTypeId(0xb0b8832625824427L, 0x889661f7684b0da0L, 0x2335ec8254d7a9e9L)).origin("1384667636723480692").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForPassage() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("HBML", "Passage", 0xb0b8832625824427L, 0x889661f7684b0da0L, 0x2335ec8254d7aa09L);
    b.class_(false, false, false);
    b.parent(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L);
    b.origin("r:662f0f43-f4fc-4ca0-87f9-029b3756b650(HBML.structure)/2537194009606466057");
    b.version(2);
    b.associate("spaceA", 0x2335ec8254d7aa0cL).target(0xb0b8832625824427L, 0x889661f7684b0da0L, 0x1c4a0aa7eed2481L).optional(false).origin("2537194009606466060").done();
    b.associate("spaceB", 0x2335ec8254d7aa0eL).target(0xb0b8832625824427L, 0x889661f7684b0da0L, 0x1c4a0aa7eed2481L).optional(false).origin("2537194009606466062").done();
    b.aggregate("devices", 0x4819fffa39c2e80fL).target(0xb0b8832625824427L, 0x889661f7684b0da0L, 0xb6c10cfea61b6eL).optional(true).ordered(true).multiple(true).origin("5195465095324559375").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForRoom() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("HBML", "Room", 0xb0b8832625824427L, 0x889661f7684b0da0L, 0x1c4a0aa7eed248fL);
    b.class_(false, false, false);
    b.super_("HBML.structure.Space", 0xb0b8832625824427L, 0x889661f7684b0da0L, 0x1c4a0aa7eed2481L);
    b.origin("r:662f0f43-f4fc-4ca0-87f9-029b3756b650(HBML.structure)/127403343607571599");
    b.version(2);
    b.property("type", 0x1c4a0aa7eed2490L).type(MetaIdFactory.dataTypeId(0xb0b8832625824427L, 0x889661f7684b0da0L, 0x1c4a0aa7eed2492L)).origin("127403343607571600").done();
    b.property("height", 0x2335ec8254d7a9e0L).type(MetaIdFactory.dataTypeId(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0x10324579ea7L)).origin("2537194009606466016").done();
    b.aggregate("windows", 0xb6c10cfea61b91L).target(0xb0b8832625824427L, 0x889661f7684b0da0L, 0xb6c10cfea61b12L).optional(true).ordered(true).multiple(true).origin("51440707317406609").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForSensor() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("HBML", "Sensor", 0xb0b8832625824427L, 0x889661f7684b0da0L, 0xb6c10cfea61a84L);
    b.class_(false, false, false);
    b.parent(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L);
    b.origin("r:662f0f43-f4fc-4ca0-87f9-029b3756b650(HBML.structure)/51440707317406340");
    b.version(2);
    b.property("type", 0xb6c10cfea61a87L).type(MetaIdFactory.dataTypeId(0xb0b8832625824427L, 0x889661f7684b0da0L, 0xb6c10cfea61adbL)).origin("51440707317406343").done();
    b.property("value", 0xb6c10cfea61a89L).type(MetaIdFactory.dataTypeId(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0x10324579ea7L)).origin("51440707317406345").done();
    b.property("model", 0x133753e11ae4ebc2L).type(PrimitiveTypeId.STRING).origin("1384667636723674050").done();
    b.associate("space", 0xb6c10cfea61b8fL).target(0xb0b8832625824427L, 0x889661f7684b0da0L, 0x1c4a0aa7eed2481L).optional(false).origin("51440707317406607").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForSpace() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("HBML", "Space", 0xb0b8832625824427L, 0x889661f7684b0da0L, 0x1c4a0aa7eed2481L);
    b.class_(false, false, false);
    b.parent(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L);
    b.origin("r:662f0f43-f4fc-4ca0-87f9-029b3756b650(HBML.structure)/127403343607571585");
    b.version(2);
    b.property("length", 0x1c4a0aa7eed248aL).type(MetaIdFactory.dataTypeId(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0x10324579ea7L)).origin("127403343607571594").done();
    b.property("width", 0x2335ec8254d7a9e3L).type(MetaIdFactory.dataTypeId(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0x10324579ea7L)).origin("2537194009606466019").done();
    b.aggregate("devices", 0xb6c10cfea61b73L).target(0xb0b8832625824427L, 0x889661f7684b0da0L, 0xb6c10cfea61b6eL).optional(true).ordered(true).multiple(true).origin("51440707317406579").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForWindow() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("HBML", "Window", 0xb0b8832625824427L, 0x889661f7684b0da0L, 0xb6c10cfea61b12L);
    b.class_(false, false, false);
    b.parent(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L);
    b.origin("r:662f0f43-f4fc-4ca0-87f9-029b3756b650(HBML.structure)/51440707317406482");
    b.version(2);
    b.property("width", 0xb6c10cfea61b17L).type(MetaIdFactory.dataTypeId(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0x10324579ea7L)).origin("51440707317406487").done();
    b.property("height", 0xb6c10cfea61b1aL).type(MetaIdFactory.dataTypeId(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0x10324579ea7L)).origin("51440707317406490").done();
    b.property("doorsNumber", 0x133753e11ae4ebc6L).type(PrimitiveTypeId.INTEGER).origin("1384667636723674054").done();
    return b.create();
  }
}
